# %% [markdown]
# # **IMPORTANT:** Please DO NOT edit this file directly. Save your own copy and open that in Colab (see more below).

# %% [markdown]
# # Week 3: Retrieval Augmented Generation (RAG)
# 
# ## Part 2: Live Demos and Code Walkthroughs
# 
# **Use Case Spotlight:** A university FAQ bot that answers student questions from the student handbook
# 
# **Outline**
# 
# 1. **Set Up**
# 2. **LLM Limitations** *(theory recap)*
#    - How LLMs Are Trained
#    - Hallucinations
# 3. **Document Ingestion**
#    - Unstructured Documents (PDFs)
#    - Web Scraping (URLs)
# 4. **Naive / Keyword Search**
# 5. **Cosine Similarity**
# 6. **Chunking Strategies**
#    - Fixed-Size
#    - Sentence-Based / Header-Based
#    - Semantic Chunking
# 7. **Embedding Models**
# 8. **Vector Storage**
# 9. **Advanced Information Retrieval**
#    - Similarity Search
#    - Top-K Selection
#    - Maximum Marginal Relevance (MMR)
#    - Context Window Retrieval
# 10. **Generation**
# 11. **University FAQ bot Use-Case**
# 12. **Completion Checklist**
# 13. **Learning Resources**
# 
# 
# 

# %% [markdown]
# ## Section 1. Set Up

# %% [markdown]
# Install the necessary libraries

# %%
# ADDED FOR DEBUGGING BROKEN CELLS (due to the runtime disconnecting frequently)
!pip uninstall -y torchvision
!pip install -q --upgrade transformers sentence-transformers langchain-huggingface

# %%
# ADDED FOR DEBUGGING (due to the runtime disconnecting frequently)
!pip uninstall -y transformers sentence-transformers
!pip install -q scikit-learn "sentence-transformers==2.7.0" "transformers==4.39.3"

# %%
# Install required libraries
!pip install -qU langchain langchain-experimental langchain-community langchain-openai langchain-text-splitters chromadb sentence-transformers openai pypdf tiktoken unstructured beautifulsoup4

# %% [markdown]
# You can run this notebook using entirely free, open-source models, or you can use OpenAI's proprietary models for state-of-the-art reasoning.
# 
# **Approach A: Open-Source** requires no API keys.
# 
# **Approach B: OpenAI API** requires an API key. We will use Google Colab's `userdata` feature to load it securely.
# ###
# <details>
# <summary>To add an OpenAI API key to your Google Colab environment securely, follow these steps:</summary>
# 
# 1. Open the Secrets Pane
# 
#     a. Look at the left-hand sidebar in your Google Colab interface.
# 
#     b. Click on the Key icon (looks like a small key). This is the Secrets pane.
# 
# 2. Add a New Secret
# 
#     a. Click on "+ Add new secret".
# 
#     b. In the Name field (left box), type: OPENAI_API_KEY
# 
#     c. In the Value field (right box), paste your actual API key (the one starting with sk-...).
# 
#   **Crucial:** Toggle the switch under the "Notebook access" column to On. This allows your specific notebook to read the key.
# 
#   </details>

# %%
import os
from google.colab import userdata

try:
    os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')
    print("OpenAI API Key loaded successfully.")
except Exception as e:
    print("No OPENAI_API_KEY found in Colab Secrets. Stick to open-source or add your key.")

# %% [markdown]
# Set up Ollama

# %%
# 1. Install Ollama command line tool
!sudo apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh
!pip install ollama

# 2. Start the Ollama server in the background and pipe logs to a file
import subprocess
import time
print("⚡ Starting Ollama server...")
process = subprocess.Popen(["ollama", "serve"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# Give the server a few seconds to wake up
time.sleep(5)

# %% [markdown]
# ## Section 2. LLM Limitations
# 
# Before diving into RAG, it's important to understand *why* we need it. This section provides a hands-on look at the
# two core limitations discussed in Part 1: **knowledge boundaries** and **hallucinations**.
# 

# %% [markdown]
# ### 2.1 How LLMs Are Trained — Knowledge Boundaries
# 
# LLMs are trained on massive datasets scraped from the internet up to a **fixed cut-off date**. They are essentially
# a **compressed representation** of everything in that training corpus. This means:
# 
# - They can answer questions about **past events, public documents, and internet discussions** in their training data.
# - They **cannot** answer questions about **present events, private data, or non-static data** that was never in
#   the training set.
# 
# Let's demonstrate this boundary below by asking an LLM a question that is clearly outside its knowledge.
# 

# %%
!pip install langchain-community langchain-core langchain-ollama

# %%
# 3. Pull the LLM Model
print("📥 Downloading the LLM...")
!ollama pull gemma3:1b

# %%
# Demonstration: LLM Knowledge Boundary
# We query the LLM directly (no RAG) with a question about private/proprietary data.
# Ensure Ollama is running from Section 1 before running this cell.

from langchain_community.llms import Ollama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

demo_llm = Ollama(model="gemma3:1b")

# Ask something the LLM cannot know (private enterprise data)
questions = [
    "What is the current dress code policy at Oakridge Academy?",  # private doc
    "What happened in the news yesterday?",                        # recency gap
    "What project deadline did we agree on in the group chat?",    # private message
    "What is the current stock price of NVIDIA?",                  # dynamic data
]

for q in questions:
    prompt = ChatPromptTemplate.from_template("Answer concisely: {question}")
    chain  = prompt | demo_llm | StrOutputParser()
    print(f"Question: {q}")
    print(f"LLM Answer: {chain.invoke({'question': q})}")
    print("-" * 60)


# %% [markdown]
# > **Observe:** The LLM either makes up an answer (hallucination) or admits it doesn't know. This is the exact problem RAG is designed to solve.
# 

# %% [markdown]
# ### 2.2 Hallucinations
# 
# A **hallucination** is a confident-sounding but factually incorrect or fabricated output from an LLM. According to Part 1, hallucinations arise from three main causes:
# 
# | Cause | Explanation |
# |---|---|
# | **Trash Training Data** | LLMs learn from noisy datasets with contradictions. Frequent falsehoods get high probability. |
# | **Reinforcement Learning Flaws** | Models are rewarded for being *helpful and confident*, not necessarily truthful. |
# | **Decoding Strategies** | Nucleus sampling introduces randomness that can push the model into low-accuracy zones. |
# 
# The cell below deliberately prompts the LLM for a fictional fact to illustrate a hallucination.
# 

# %%
# Demonstration: Triggering a Hallucination
# We ask the model a plausible-sounding but entirely fictional question.
# Watch it confidently fabricate an answer.

hallucination_prompt = ChatPromptTemplate.from_template(
    "You are a confident assistant. Answer this question in 2-3 sentences: {question}"
)
hallucination_chain = hallucination_prompt | demo_llm | StrOutputParser()

tricky_question = (
    "What was the exact GPA requirement for the Oakridge Academy Honor Roll in 2018, "
    "and what special privileges did it grant?"
)

print(f"Question: {tricky_question}\n")
print("LLM Answer (likely hallucinated):")
print(hallucination_chain.invoke({"question": tricky_question}))
print("\n⚠️  The LLM invented details that are NOT in any real document.")


# %% [markdown]
# ### [EXERCISE] Detect Your Own Hallucination
# 
# 1. Ask the LLM a question about your own organisation, university, or team that **no public dataset would contain**.
# 2. Record its response below.
# 3. In a Markdown cell, annotate which parts of the response are fabricated and explain which hallucination cause (from the table above) most likely produced it.
# 

# %%
# Add your code here!

hallucination_prompt = ChatPromptTemplate.from_template(
    "You are a confident assistant. Answer this question in 2-3 sentences: {question}"
)
hallucination_chain = hallucination_prompt | demo_llm | StrOutputParser()

tricky_question = (
    "If you bring in a plastic straw into university grounds, what are the implications,"
    "and what are the DL privileges for the College of Computer Studies"
)

print(f"Question: {tricky_question}\n")
print("LLM Answer (likely hallucinated):")
print(hallucination_chain.invoke({"question": tricky_question}))
print("\n⚠️  The LLM invented details that are NOT in any real document.")

# %% [markdown]
# 

# %% [markdown]
# ## Section 3. Document Ingestion

# %% [markdown]
# 
# ### 2.1 Unstructured Documents (PDFs)
# 
# Upload the [Student Handbook PDF](https://) to this colab file by following the ff steps

# %%
!pip -q install langchain_community pypdf

# %%
from langchain_community.document_loaders import PyPDFLoader

loader_pdf = PyPDFLoader("/content/student_handbook.pdf")
docs_pdf = loader_pdf.load()

print(docs_pdf)

# %% [markdown]
# 
# ### 2.2 Web Scraping (URLs)

# %%
from langchain_community.document_loaders import WebBaseLoader

loader_web = WebBaseLoader("https://stratpoint.com/")
docs_web = loader_web.load()
print(f"Loaded Web Page. Number of documents: {len(docs_web)}")

# %% [markdown]
# ### [EXERCISE] Multiple Document Ingestion
# ### [EXERCISE] Try out 3 other document loaders
# https://docs.langchain.com/oss/python/integrations/document_loaders

# %%
!pip install langchain-community yt-dlp youtube-transcript-api

# %%
!pip install pymupdf4llm langchain-community

# %%
!pip install unstructured langchain-community

# %%
from langchain_community.document_loaders import YoutubeLoader

# Youtube URL-based Transcript Loader
loader = YoutubeLoader.from_youtube_url(
    "https://www.youtube.com/watch?v=rsxpkRRBp80",  # The Adventure Time Episode No One Understands"
    add_video_info=False,
    language=["en"],
)

docs = loader.load()

print(f"Number of documents loaded: {len(docs)}")
print(f"Characters in transcript: {len(docs[0].page_content)}")
print("\n--- Transcript Snippet ---")
print(docs[0].page_content[:500])
print("\n--- Metadata ---")
print(docs[0].metadata)

# %%
import pymupdf4llm
from langchain_core.documents import Document

# Download a sample PDF to load (any PDF file path works)
!wget -q -O sample.pdf https://link.springer.com/content/pdf/10.1186/s41239-017-0062-1.pdf  # "Vlachopoulos & Makri"

md_text = pymupdf4llm.to_markdown("sample.pdf")

# Wrap as a LangChain Document (compatible with the rest of your RAG pipeline)
docs = [Document(page_content=md_text, metadata={"source": "sample.pdf"})]

print(f"Number of documents: {len(docs)}")
print(f"Total characters: {len(docs[0].page_content)}")
print("\n--- Markdown Snippet ---")
print(docs[0].page_content[:800])

# %%
from langchain_community.document_loaders import UnstructuredURLLoader

urls = [
    "https://finalfantasy7remake.wiki.fextralife.com/Mako_Reactor_1",
    "https://finalfantasywiki.com/wiki/Mako_Reactor",
]

loader = UnstructuredURLLoader(urls=urls)
docs = loader.load()

print(f"Number of documents loaded: {len(docs)}")

for i, doc in enumerate(docs):
    print(f"\n--- Document {i+1} ---")
    print(f"Source : {doc.metadata.get('source')}")
    print(f"Length : {len(doc.page_content)} characters")
    print(f"Snippet: {doc.page_content[:300]}")

# %% [markdown]
# ## Section 4. Naive / Keyword Search
# 
# Before we use vector embeddings, let's understand the baseline approach covered in Part 1: **keyword search**.
# This is the simplest form of retrieval — we extract keywords from a query and scan each text block for their
# presence.
# 
# **Limitations (as discussed in lecture):**
# - **RIGID** — Wrong keyword identification, synonyms cause misses, false positives.
# - **SLOW** — Requires one-by-one scanning of every block.
# 
# Let's implement it from scratch and observe its weaknesses.
# 

# %%
import re

# Use the raw handbook pages we loaded in Section 3
raw_chunks = []
for doc in docs_pdf:
    # Split each page's content by double newlines into standalone paragraph sections
    sections = doc.page_content.split('\n\n')
    for section in sections:
        clean_section = section.strip()
        if clean_section:  # Drop empty strings
            raw_chunks.append(clean_section)

def keyword_search(query: str, pages: list, top_n: int = 3) -> list:
    """Naive keyword search: extract keywords, scan pages, rank by hit count."""
    # Strip stopwords and split into keywords
    stopwords = {"what", "is", "the", "a", "an", "of", "in", "for", "are", "and", "to", "do", "i", "if", "should"}
    keywords = [w.lower() for w in re.findall(r'\w+', query) if w.lower() not in stopwords]
    print(f"Extracted keywords: {keywords}\n")

    results = []
    for i, page in enumerate(pages):
        page_lower = page.lower()
        hits = sum(1 for kw in keywords if kw in page_lower)
        results.append((hits, i, page))

    results.sort(reverse=True)
    return results[:top_n]


query_naive = "What is the dress code for students?"
print(f"Query: {query_naive}\n")
top_results = keyword_search(query_naive, raw_chunks)

for hits, page_idx, content in top_results:
    print(f"--- Page {page_idx + 1} | Keyword Hits: {hits} ---")
    print(content[:400].strip())
    print()


# %%
# Now try a synonym query — this is where keyword search FAILS
synonym_query = "Are jeans allowed on Thursdays?"
print(f"Synonym Query: {synonym_query}\n")
synonym_results = keyword_search(synonym_query, raw_chunks)

for hits, page_idx, content in synonym_results:
    print(f"--- Page {page_idx + 1} | Keyword Hits: {hits} ---")
    print(content[:300].strip())
    print()

print("\n⚠️  Notice: the correct page about dress code may NOT be the top result")
print("   because synonym words like 'wear' and 'pupils' don't appear verbatim.")


# %%
# Now try a query that causes a FALSE POSITIVE — where keyword search "succeeds" but gets the wrong context
false_positive_query = "How do I join the school band?"
print(f"False Positive Query: {false_positive_query}\n")
false_positive_results = keyword_search(false_positive_query, raw_chunks)

for hits, page_idx, content in false_positive_results:
    print(f"--- Page {page_idx + 1} | Keyword Hits: {hits} ---")
    print(content[:300].strip())
    print()

print("\n⚠️  Notice: The top result is a FALSE POSITIVE!")

# %% [markdown]
# ### [EXERCISE] Keyword Search Failure Cases
# 
# 1. Try **two more queries** that use **paraphrased or synonym language** (e.g., asking about 'skipping class' instead of 'absences').
# 2. Compare the keyword search results against the actual document page you would expect to retrieve.
# 3. In a Markdown cell, explain: *why does semantic (embedding-based) search solve these problems?*
# 

# %%
# Paraphrase: Absences -> Skipping Class

query_paraphrase_1 = "What happens if I skip class too many times?"
print(f"Query 1 (Paraphrased): {query_paraphrase_1}\n")
results_1 = keyword_search(query_paraphrase_1, raw_chunks)

for hits, page_idx, content in results_1:
    print(f"--- Chunk {page_idx + 1} | Keyword Hits: {hits} ---")
    print(content[:400].strip())
    print()

print("⚠️  Expected: chunks about attendance/absence policy")
print("   Got: chunks matching 'class', 'times' out of context — the word 'absences' never appeared in the query.")

# %%
# Synonym: Examination -> Test ; Academic Dishonesty -> Cheat

query_paraphrase_2 = "Can I get expelled for cheating on a test?"
print(f"Query 2 (Synonym): {query_paraphrase_2}\n")
results_2 = keyword_search(query_paraphrase_2, raw_chunks)

for hits, page_idx, content in results_2:
    print(f"--- Chunk {page_idx + 1} | Keyword Hits: {hits} ---")
    print(content[:400].strip())
    print()

print("⚠️  Expected: chunks about academic dishonesty / examination rules")
print("   Got: irrelevant chunks — 'cheating' and 'test' don't match 'academic dishonesty' or 'examination'.")

# %% [markdown]
# ## Semantic-based (Embedding-based) Search VS. Keyword Search
# - **Keyword search** delves into the question: "Do these same letters appear in the text?" Which is effective for fast lookups of specific keywords, but is ineffective against words with similar meaning (e.g. synonyms)
# - **Semantic search** takes a step further than this. By using a model trained specifically on a multitude of text data, it is able to correctly map the semantic relationships between different words and phrases. The model is then fed the raw text data to find words with similarities, as it already has an understanding of the semantic relationships between the words; enabling synonym-based word search.

# %% [markdown]
# ## Section 5. Cosine Similarity
# 
# In Part 1, we learned that **embeddings** map words into numerical vectors in a high-dimensional space, and
# that **cosine similarity** is the standard metric to measure how *conceptually close* two vectors are.
# 
# The formula for cosine similarity between vectors **A** and **B** is:
# 
# $$\cos(\theta) = \frac{\mathbf{A} \cdot \mathbf{B}}{\|\mathbf{A}\| \|\mathbf{B}\|}$$
# 
# - A score close to **1.0** → near-identical meaning (e.g., "good" vs "great").
# - A score close to **0.0** → unrelated concepts.
# - A score close to **-1.0** → opposite meanings (e.g., "good" vs "bad").
# 
# Let's compute cosine similarity manually using `sklearn` before handing that job off to ChromaDB.
# 

# %%
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import numpy as np

# Use a lightweight open-source sentence encoder
print("Loading sentence encoder (first run may take a minute)...")
encoder = SentenceTransformer("all-MiniLM-L6-v2")

# --- Word-level example (mirrors the lecture slides) ---
word_pairs = [
    ("good", "great"),
    ("good", "bad"),
    ("king", "queen"),
    ("king", "bicycle"),
]

print("\n--- Cosine Similarity Between Word Pairs ---")
for a, b in word_pairs:
    vecs = encoder.encode([a, b])
    sim  = cosine_similarity([vecs[0]], [vecs[1]])[0][0]
    print(f"  cos_sim('{a}', '{b}') = {sim:.4f}")


# %%
# --- Sentence-level example: query vs document chunks ---
query_sentence = "What are the rules about student uniforms?"

candidate_sentences = [
    "All students must wear a navy blue blazer and khaki trousers.",  # relevant
    "The library opens at 8 AM every weekday.",                      # irrelevant
    "Approved Oakridge polo shirts are required on Fridays.",         # relevant
    "Academic probation applies when GPA falls below 2.00.",          # irrelevant
]

query_vec      = encoder.encode([query_sentence])
candidate_vecs = encoder.encode(candidate_sentences)

scores = cosine_similarity(query_vec, candidate_vecs)[0]

print(f"Query: '{query_sentence}'\n")
print("Cosine Similarities:")
ranked = sorted(zip(scores, candidate_sentences), reverse=True)
for score, sent in ranked:
    print(f"  [{score:.4f}]  {sent}")

print("\n✅ The most relevant chunks rise to the top — this is exactly how vector search works.")


# %% [markdown]
# ### [EXERCISE] Cosine Similarity Explorer
# 
# 1. Pick **three different queries** related to the student handbook (e.g., about attendance, grading, or health rules).
# 2. For each query, compute cosine similarity against **all 5 pages** of the handbook.
# 3. Does the highest-scoring page always contain the most relevant answer? Note any surprising results.
# 

# %%
queries = [
    "What actions result in Academic Probation?",
    "How does the school handle emergencies?",
    "Can I wear jeans to school on a Tuesday?"
]

print("Cosine Similarities:")

# Calculate similarities, rank the, print top 2 pages per query
for q in queries:
    print(f"Query: '{q}'")
    q_vec = encoder.encode([q])

    sims = cosine_similarity(q_vec, encoder.encode(raw_chunks))[0]

    ranked = sorted(zip(sims, range(len(raw_chunks)), raw_chunks), reverse=True)

    for score, page_idx, content in ranked[:2]:
        print(f"  [Score: {score:.4f}] Page {page_idx + 1}: {content[:100].strip()}...")
    print("-" * 60)

# %% [markdown]
# **Answer**
# 1. There is a successful semantic match for the first query "Academic Probation" on page 3 (Academic Policies) at 0.5364, showing the proper semantic mapping of "academic probation".
# 2. Query 2 scored at 0.4640, mapping it to Page 5 (Operations, Dress Code, and Health). Despite the emergencies being located later on in page 5, the top snippet still includes the daily standard uniform. While it did correctly identify the section as "OPERATIONS, DRESS CODE, AND HEALTH", it wasn't able to factor in for the extra text preceding the actual queried keywords, putting all of them under one section.
# 3. Query 3 scored at 0.3557, and correctly matched the Daily Standard Uniform block of text, being under the same "OPERATIONS, DRESS CODE, AND HEALTH", allowing it to properly navigate towards the page with the context in question. Even though "wear" was not a specific keyword under the uniform section, it was able to identify the semantic similarities and correctly map towards the correct page.

# %% [markdown]
# ## Section 6. Chunking
# 

# %%
# Set the loaded PDF as the document to by chunked
documents = docs_pdf

# %% [markdown]
# ### 3.1 Fixed-Size
# 
# Traditional fixed-size chunking is the most basic way to split text, acting like a digital cookie cutter. It completely ignores both grammar and meaning, simply counting out a set number of characters or tokens (like 100 or 500) and chopping the text right there.
# 
# Here is how it works under the hood:
# 
# * **The Process:** You define a strict **chunk size** (e.g., 200 characters) and a **chunk overlap** (e.g., 50 characters) so consecutive chunks share some text to prevent total loss of context.
# * **The Challenge:** Because it only counts characters, it frequently slices text right in the middle of a word, a sentence, or a crucial paragraph.
# * **The Result:** It is incredibly fast and computationally cheap, but it often leaves LLMs with fragmented, confusing half-thoughts.

# %%
!pip install -q langchain-text-splitters

# %%
from langchain_text_splitters import CharacterTextSplitter

# Method 1: Fixed-Size Chunking

# Initialize splitter
text_splitter = CharacterTextSplitter(
  separator="\n\n",
  chunk_size=1000,
  chunk_overlap=200
)

chunks = text_splitter.split_documents(documents)

# Review the results
print(f"Split document into {len(chunks)} chunks.")

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk.page_content.strip())

# %% [markdown]
# ### [EXERCISE] Vary the chunk size, chunk overlap, and separators
# 
# When configuring the splitter, you will interact with three main parameters:
# 
# - `chunk_size`: The maximum number of characters (or tokens) that a single chunk can contain.
# 
# - `chunk_overlap`: The number of characters that consecutive chunks share. Having an overlap creates a "sliding window" effect, ensuring that context at the boundary of a cut isn't completely lost.
# 
# - `separators`: The custom list of characters you want the splitter to recursively loop through.

# %% [markdown]
# #### Sub-Task 1: Modifying `chunk_size` and `chunk_overlap`
# 
# Modify the `chunk_size` to `300` and the `chunk_overlap` to `50`. Run the splitter again on the sample text and analyze how the boundaries change.
# 
# How many total chunks did you generate this time compared to before? Look closely at the overlapping regions—did this setup do a better job of keeping adjacent ideas connected?

# %%
# Add your code here!
splitter_st1 = CharacterTextSplitter(
  separator="\n\n",
  chunk_size=300,
  chunk_overlap=50
)
chunks_st1 = splitter_st1.split_documents(docs_pdf)
print(f"Sub-Task 1: Split document into {len(chunks_st1)} chunks.")

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk.page_content.strip())

# %% [markdown]
# #### Sub-Task 2: Breaking `chunk_size` and `chunk_overlap`
# 
# Now, intentionally break the configuration by setting your `chunk_size` to `100` and your `chunk_overlap` to `110`.
# 
# Run the code and observe the behavior. What happens conceptually and programmatically when your overlap is larger than your total chunk size? Why must `chunk_size` always be strictly greater than `chunk_overlap`?

# %%
# Add your code here!
try:
    splitter_st2 = CharacterTextSplitter(
      separator="\n\n",
      chunk_size=100,
      chunk_overlap=110
    )
except ValueError as e:
    print(f"Sub-Task 2 Error: {e}")

# %% [markdown]
# #### Sub-Task 3: Varying Separators
# 
# Imagine you are chunking a chat transcript or a script where dialogue changes are marked by a dash (e.g., `"- Speaker A:"`).
# 
# Try passing a custom list to the `separators` parameter—such as `["\n\n", "\n-", " ", ""]`. Test it with a custom piece of text. How does adding a specific character sequence like `"\n-"` force the splitter to respect conversational boundaries instead of cutting mid-sentence?

# %%
# Add your code here!
dialogue_text = "Speaker A: Ngunit!\n- Speaker B: Ahm, Subalit!\n- Speaker A: Datapwat, Bagamat?"
dialogue_splitter = CharacterTextSplitter(
    separator="\n- ",
    chunk_size=30,
    chunk_overlap=0
)
print("Sub-Task 3 Chunks:", dialogue_splitter.split_text(dialogue_text))

# %% [markdown]
# We can try out recursively splitting text as well!
# 
# Instead of blindly cutting text at a hard character limit, the recursive splitter evaluates a prioritized list of separators—by default: `["\n\n", "\n", " ", ""]`.
# 
# Here is the step-by-step logic it executes:
# 
# 1. **Paragraphs** (`\n\n`): It first attempts to split the text by double newlines. If the resulting paragraphs are smaller than your target chunk_size, it leaves them alone.
# 
# 2. **Sentences** (`\n`): If a single paragraph is still larger than your chunk_size, the splitter moves to the next separator in the list and splits that paragraph into individual lines.
# 
# 3. **Words** (` `): If a single line is still too large, it splits it by spaces into individual words.
# 
# 4. **Characters** (`""`): As a last resort, if a single word exceeds the chunk size, it splits the word down to individual characters to strictly respect the limit.
# 
# By using this cascading logic, the splitter ensures that paragraphs and sentences are kept together for as long as mathematically possible, preserving the natural flow of information.

# %%
from langchain_text_splitters import RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter(
  chunk_size=1000,
  chunk_overlap=200
)

chunks = text_splitter.split_documents(documents)

# Review the results
print(f"Split document into {len(chunks)} chunks.")

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk.page_content.strip())

# %% [markdown]
# ### 3.2 Sentence-Based
# 
# To prepare text for AI models, we use sentence chunking to break large blocks of text into individual, grammatically correct sentences so information isn't awkwardly cut in half. To do this, we install NLTK (Natural Language Toolkit) and download its Punkt tokenizer, which is a pre-trained statistical model.
# 
# Here is exactly how it works under the hood:
# 
# - **The Challenge:** Computers don't inherently know if a period means the end of a sentence or just an abbreviation (like "Gen. Z" or "e.g.").
# 
# - **The Solution (Punkt):** Punkt looks at the words surrounding punctuation to smartly decide where a sentence actually ends.
# 
# - **The Result**: It cleanly slices your text into a clean list of complete sentences, ready for the next steps in your pipeline.

# %%
!pip install -q langchain langchain-community nltk

# %%
import nltk
from langchain_text_splitters import NLTKTextSplitter

# Download the required tokenization models (only needs to be run once)
nltk.download('punkt')
nltk.download('punkt_tab')

# %%
# Initialize the NLTK splitter.
# chunk_size here represents the maximum characters per chunk, but it respects sentence boundaries.
text_splitter = NLTKTextSplitter(chunk_size=150, chunk_overlap=0)

chunks = text_splitter.split_documents(documents)

# Review the results
print(f"Split document into {len(chunks)} chunks.")

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk.page_content.strip())

# %% [markdown]
# ### [EXERCISE] Vary the chunk size, chunk overlap, and separators
# 
# Similar to the previous exercise, try varying the chunk size, chunk overlap, and separators

# %% [markdown]
# #### Sub-Task 1: Testing the Abbreviations Trap
# Compare how the `NLTKTextSplitter` handles the words `Dr.`, `a.m.`, and `Corp.` versus how a standard character splitter would handle them if you set a very small `chunk_size` (e.g., `40`).
# 
# Does the NLTK splitter safely keep `"Dr. Smith arrived at the lab at 8:00 a.m."` as a single, unbroken sentence, or does it slice it at the abbreviations? Why is this important for data integrity?

# %%
# Add your code here!
abbrev_text = "Dr. Smith arrived at the lab at 8:00 a.m."
char_splitter = RecursiveCharacterTextSplitter(chunk_size=40, chunk_overlap=0)
nltk_splitter = NLTKTextSplitter(chunk_size=40, chunk_overlap=0)

print("Character Splitter:", char_splitter.split_text(abbrev_text))
print("NLTK Splitter:", nltk_splitter.split_text(abbrev_text))

# %% [markdown]
# **Answer**
# The character splitter blindly slices the context at "a.m." due to the character limit. NTLK, on the other hand, properly recognizes that Dr. and a.m. are not terminal periods, and thus, are still part of the same context.

# %% [markdown]
# #### Sub-Task 2: Finding the Sentence Ceiling
# Keep your `chunk_size` at `120`, but add a massive, continuous sentence to the `tricky_text` string that is well over 200 characters long (e.g., a long, rambling run-on sentence). Run the splitter.
# 
# What happens when an individual sentence is inherently larger than your configured `chunk_size`? Does NLTK force a cut mid-sentence, or does it expand the chunk size dynamically to preserve the sentence?

# %%
# Add your code here!
run_on_text = "Lorem ipsum dolor sit amet consectetur adipiscing elit quisque faucibus ex sapien vitae pellentesque sem placerat in id cursus mi pretium tellus duis convallis tempus leo eu aenean sed diam urna tempor pulvinar vivamus fringilla lacus nec metus bibendum egestas."
nltk_overlap_splitter = NLTKTextSplitter(chunk_size=120, chunk_overlap=30)
print("\nNLTK Run-on Split:", nltk_overlap_splitter.split_text(run_on_text))

# %% [markdown]
# **Answer**
# When the sentence exceeds the chunk size (chunk_size), NTLK keeps the whole sentence, beyond the given character limit.
# 
# 

# %% [markdown]
# #### Sub-Task 3: Adding Overlap to Sentences
# Modify your `NLTKTextSplitter` configuration to include a `chunk_overlap` of `30`.
# 
# Since NLTK operates on sentence boundaries, how does it handle character overlap? Does it pull the last few *words* of the previous sentence into the next chunk, or does it grab the entire preceding *sentence*? Examine the output closely.

# %%
# Add your code here!
nltk_overlap_splitter = NLTKTextSplitter(chunk_size=120, chunk_overlap=30)
print("\nNLTK Run-on Split:", nltk_overlap_splitter.split_text(run_on_text))

# %% [markdown]
# **Answer**
# When using chunk_overlap, NLTK takes the entire preceding sentence into the new chunk, without the previous 200 character limit taken into consideration.
# 
# 

# %% [markdown]
# ### 3.3 Semantic Chunking
# 
# Semantic chunking groups text based on its actual meaning rather than rigid rules or punctuation. By using an embedding model to turn sentences into mathematical vectors, it calculates how conceptually similar they are and groups related ideas together.
# 
# Here is how it works under the hood:
# 
# - **The Challenge:** Traditional chunkers might cut a paragraph in half mid-thought, destroying the context an LLM needs to understand it.
# 
# - **The Solution (Embeddings):** Semantic chunking analyzes the sentences and measures the conceptual "distance" between them.
# 
# - **The Result:** It draws a boundary only when the topic completely shifts, keeping relevant information grouped together in cohesive chunks.

# %% [markdown]
# First, we must set up an embeddings model.

# %%
import subprocess
import time

# EDIT: Script kept breaking, had to reconfigure the ollama import
subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(5)

print("📥 Downloading the embedding model...")
!ollama pull nomic-embed-text
print("🎉 Ollama is ready to go!")

# %%
!pip install -q langchain langchain-ollama langchain-experimental

# %%
from langchain_ollama import OllamaEmbeddings

# Initialize the free Ollama embeddings pointing to your local Colab instance
embeddings = OllamaEmbeddings(model="nomic-embed-text")

# %% [markdown]
# Then, we can set up the text splitter!

# %%
from langchain_experimental.text_splitter import SemanticChunker

# Setup the semantic chunker
text_splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile"
)

# Split the text
chunks = text_splitter.split_documents(documents)

# Review the results
print(f"Split document into {len(chunks)} chunks.")

for i, chunk in enumerate(chunks):
    print(f"\n--- Chunk {i+1} ---")
    print(chunk.page_content.strip())

# %% [markdown]
# ### [EXERCISE] Vary the `breakpoint_threshold_type`
# 
# There are 3 commonly used Breakpoint Threshold Types:
# - **Percentile:** Splits text based on a percentile of distance drops between sentences (e.g., any drop in the top 10%).
# - **Standard Deviation:** Splits text when a distance drop exceeds a specified number of standard deviations from the mean.
# - **Interquartile Range (IQR):** Splits text based on the statistical interquartile range, making it highly robust against extreme outliers.
# 
# You can also try varying the `breakpoint_threshold_amount` — the specific numerical value (the percentile rank, number of standard deviations, IQR multiplier, or raw gradient threshold) used to trigger a split.

# %%
# Add your code here!
std_text_splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="standard_deviation",
    breakpoint_threshold_amount=1.25
)

std_chunks = std_text_splitter.split_documents(docs_pdf)
print(f"Standard Deviation Splitter created {len(std_chunks)} chunks.")

# %% [markdown]
# ### [EXERCISE] Exploring Advanced LangChain Splitters
# 
# Different data formats require different splitting strategies. LangChain provides specialized splitters that understand the structural rules of specific file types.
# 
# 1. Open the [LangChain Text Splitters Reference API](https://reference.langchain.com/python/langchain-text-splitters).
# 2. Choose **one** specialized splitter to experiment with, such as:
#    * `MarkdownTextSplitter` (splits naturally by markdown headers)
#    * `PythonCodeTextSplitter` (respects code block boundaries and syntax)
#    * `TokenTextSplitter` (chunks by exact LLM token counts rather than characters)
# 3. Write a code cell below to initialize your chosen splitter, test it on a custom sample text, and print the output chunks.
# 
# How does your chosen splitter preserve document context better than a standard character splitter?

# %%
# Add your code here!
from langchain_text_splitters import MarkdownTextSplitter

markdown_sample = """
# Chapter 1: Hello World
README Sample README
## Research Questions
What is a dog?
# Chapter 2: RRL
A dog can be a wolf.
"""

md_splitter = MarkdownTextSplitter(chunk_size=50, chunk_overlap=0)
md_chunks = md_splitter.create_documents([markdown_sample])

for i, chunk in enumerate(md_chunks):
    print(f"Chunk {i+1}: {chunk.page_content.strip()}")

# %% [markdown]
# **Answer**
# The MarkdownTextSplitter segmented it via the "#" character, effectively separating it logically via markdown rules.

# %% [markdown]
# ## Section 7. Embedding Models

# %% [markdown]
# This embedding step simply takes that list and translates each text chunk into a dense numerical vector that captures its core concepts, preparing the data for the AI to search through later.
# 
# This is exactly the same way the embeddings model in semantic chunking was set up.

# %%
# added for debugging specific cells
import subprocess
import time

subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(10) # Give the server time to fully wake up

print("📥 Downloading the embedding model...")
!ollama pull nomic-embed-text
print("🎉 Ollama is ready to go!")

# %%
# Pull the embedding model (nomic-embed-text is highly recommended and lightweight)
print("📥 Downloading the embedding model...")
!ollama pull nomic-embed-text

print("🎉 Ollama is ready to go!")

# %%
from langchain_community.embeddings import OllamaEmbeddings

# Initialize the embedding model (Ensure your Ollama background server is running!)
embeddings_model = OllamaEmbeddings(model="nomic-embed-text")

# %% [markdown]
# If you want to generate the vectors separately, you can run the following:

# %%
# Send the list to Ollama to generate the mathematical vectors
print(f"Generating embeddings for {len(chunks)} chunks...")
vectors = embeddings_model.embed_documents(chunks)

# Inspect the results
print("✨ Embeddings successfully generated!")
print(f"Total vectors created: {len(vectors)}")
print(f"Dimensions per vector: {len(vectors[0])}")

# %% [markdown]
# ### [EXERCISE] Try using a different open-source embedding model (e.g., BGE-M3, E5-Large) and compare their performance trade-offs (e.g., latency, size, MTEB score) for the FAQ bot knowledge base.

# %%
# Add your code here!
!pip install -q sentence-transformers langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings

print("Downloading BGE-Small model...")
hf_embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")

sample_vec = hf_embeddings.embed_query("Testing HuggingFace embeddings.")
print(f"Generated vector with dimension: {len(sample_vec)}")

# %% [markdown]
# ## Section 8. Vector Storage
# 
# Now that we have chopped our raw text into distinct chunks, we need a way to store them so an LLM can easily search through them later. This is where ChromaDB and our Ollama embedding model work together as a team.
# 
# Here is exactly how this process unfolds under the hood:
# 
# - **The Indexing Process (Chroma.from_texts):** When we pass our list of chunks to Chroma alongside our embeddings_model, we aren't just saving plain text. Chroma automatically sends each text chunk to Ollama, receives its unique mathematical vector, and pairs them up in the database.
# 
# - **The Semantic Filing Cabinet:** Think of ChromaDB as a giant, multi-dimensional map. It uses those vectors from Ollama to physically plot your chunks in a "meaning space." Chunks about similar topics are placed right next to each other, while completely unrelated topics are placed far apart.
# 
# - **The Retrieval Magic (similarity_search):** When you ask the database a question, Chroma uses Ollama one last time to turn your query into a vector. It then looks at its map, finds the chunks closest to your question's mathematical location, and pulls them instantly—even if your question didn't use the exact same words as the text.

# %%
!pip install opentelemetry-api opentelemetry-sdk langchain-chroma

# %%
# 1. Force uninstall the conflicting packages to clear the cache
!pip uninstall -y opentelemetry-api opentelemetry-sdk langchain-chroma

# 2. Reinstall them cleanly so they grab the latest, matching versions
!pip install opentelemetry-api opentelemetry-sdk langchain-chroma

# %%
import subprocess
import time

subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(10)

print("📥 Downloading the embedding model...")
!ollama pull nomic-embed-text
print("🎉 Ollama is ready to go!")

# %%
from langchain_chroma import Chroma

# Create an in-memory Chroma database populated with your text and embedding model
print("Creating Chroma vector database and indexing chunks...")
db = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings_model
)

print("🚀 Chroma database is ready and fully indexed!")

# %% [markdown]
# ## Section 9. Advanced Information Retrieval

# %% [markdown]
# ### 6.1 Similarity Search
# Once text is inside our vector database, we retrieve information using Similarity Search.
# - The Concept: Traditional databases look for exact word matches (keyword search). Vector databases look for conceptual matches. ChromaDB takes your search phrase, turns it into a vector via Ollama, and calculates the mathematical "distance" between your query and your stored chunks.
# - Chroma's Distance Metric: By default, Chroma calculates squared Euclidean distance ($L^2$ distance). Lower numbers mean the documents are closer together and more similar, while higher numbers mean they are different.
# 
# While fetching the closest chunks works fine, a big issue in production RAG systems is redundancy. If your document repeats the same fact three times across different paragraphs, a basic Top-K search will return all three identical paragraphs, wasting your budget and cluttering the AI's memory.
# 
# To fix this, we use two different selection strategies:
# 
# - Top-K Selection (Pure Relevance): It ruthlessly picks the absolute closest items to your query, even if they say the exact same thing.
# 
# - Maximum Marginal Relevance (MMR) (Relevance + Diversity): MMR is a balancing act. It initially looks at a wide pool of candidate chunks (fetch_k). It grabs the closest match first, but before picking the second or third match, it checks how similar they are to the chunks it already picked. If a chunk is redundant, MMR penalizes it and looks for a different, distinct piece of information.

# %%
query = "What is the university dress code?"

# %% [markdown]
# #### 6.2.1 Top-K Selection

# %%
# Approach 1: Pure Top-K (High risk of repetitive content)
print("Fetching pure Top-K results...")
top_k_results = db.similarity_search(query, k=3)

print(f"Found {len(top_k_results)} matching chunks:\n")
for i, doc in enumerate(top_k_results):
    print(f"--- Chunk {i+1} ---")
    print(doc.page_content)

# %% [markdown]
# If you want to see the scores, use `similarity_search_with_score`.

# %%
# Run search with distance scores (Seeing the math)
# This returns a list of tuples: (Document object, distance_score)
results_with_scores = db.similarity_search_with_score(query, k=3)

print("\n--- Top Matching Results with Scores ---")
for doc, score in results_with_scores:
    print(f"\n[Distance Score: {score:.4f}] (Lower = More Similar)")
    print(f"Content: {doc.page_content[:150]}...")

# %% [markdown]
# #### 6.2.2 Maximum Marginal Relevance (MMR)

# %%
# Approach 2: Maximal Marginal Relevance (Diverse results)
print("Fetching MMR results for better diversity...")
mmr_results = db.max_marginal_relevance_search(
    query,
    k=3,          # The final number of chunks to return to the LLM
    fetch_k=10,   # Look at the top 10 closest chunks initially before filtering for diversity
    lambda_mult=0.5 # Balance factor (1.0 = pure relevance, 0.0 = pure diversity)
)

print(f"Found {len(mmr_results)} matching chunks:\n")
for i, doc in enumerate(mmr_results):
    print(f"--- Chunk {i+1} ---")
    print(doc.page_content)

# %% [markdown]
# ### 6.3 Context Window Retrieval
# 
# The **Context Window** strategy, discussed in Part 1, is an alternative to Top-K. Instead of returning only the
# highest-similarity chunk, it also returns the **neighboring chunks** (the chunks immediately before and after
# the best match). This is useful when:
# 
# - Related information is spread across adjacent paragraphs (e.g., a multi-step policy).
# - Your documents have a clear structure like guides, lessons, or directories.
# - A small chunk size means individual chunks lose context on their own.
# 

# %%
from langchain_text_splitters import RecursiveCharacterTextSplitter
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity  # Assuming you are using sklearn for this

# Re-split with small chunks so neighbours are meaningful
small_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=0)
small_chunks   = small_splitter.split_documents(docs_pdf)
small_texts    = [c.page_content for c in small_chunks]

window_query = "What are the rules around uniforms on Fridays?"

# Use the 'embeddings_model' variable with the proper LangChain methods
print("Embedding chunks and query...")
all_vecs   = embeddings_model.embed_documents(small_texts)
query_vec2 = [embeddings_model.embed_query(window_query)]

# Calculate similarities
sims        = cosine_similarity(query_vec2, all_vecs)[0]
best_idx    = int(np.argmax(sims))

window_size = 1  # how many neighbours to grab on each side
start = max(0, best_idx - window_size)
end   = min(len(small_texts) - 1, best_idx + window_size)

print(f"\nQuery: {window_query}")
print(f"Best matching chunk index: {best_idx} (similarity: {sims[best_idx]:.4f})")
print(f"Returning chunks {start} → {end} (context window = ±{window_size})\n")

for i in range(start, end + 1):
    label = " ← BEST MATCH" if i == best_idx else ""
    print(f"--- Chunk {i}{label} ---")
    print(small_texts[i].strip())
    print()

# %% [markdown]
# ### [EXERCISE] Tune the Window Size
# 
# Change `window_size` to `2` and then `3`. Answer the following:
# 1. At what window size does the context become helpful vs. noisy?
# 2. When would you prefer Context Window retrieval over MMR? Give an example use case.
# 

# %%
# Add your code here!
test_window_sizes = [2, 3]

for w_size in test_window_sizes:
    start = max(0, best_idx - w_size)
    end = min(len(small_texts) - 1, best_idx + w_size)

    print(f"\n--- Context Window (±{w_size}) ---")
    print(f"Total chunks retrieved: {end - start + 1}")
    for i in range(start, end + 1):
        label = " [BEST MATCH]" if i == best_idx else ""
        print(f"  Chunk {i}{label}: {small_texts[i][:60]}...")

# %% [markdown]
# **Answer**
# 1. Performs well at window_size = 1 or 2, providing just enough context to understand whether a policy is applicable or not. It starts to become noisy at window_size = 3, including unrelated policies outside of the desired context.
# 2. Context window is best when dealing with order-sensitive procedural or sequential data, while MMR is best at dealing with bulky, information-dense documents.

# %% [markdown]
# ## Section 10. Generation

# %% [markdown]
# Now that our data is chunked and stored, it is time to look at the **Generation** stage of RAG. How exactly does adding context change an LLM's response?
# 
# To understand this, we will run a comparative experiment testing the exact same question against **three distinct architectures**:
# 1. **No Context:** The model relies purely on its pre-trained internal weights.
# 2. **Full Context (Context Stuffing):** We paste the entire un-chunked document directly into the prompt.
# 3. **Retrieval-Augmented Generation (RAG):** We use a vector database to search, retrieve only the most relevant *semantic chunks*, and pass those to the model.

# %% [markdown]
# First, let's set up the LLM and the query

# %%
!ollama pull gemma3:1b

# Or specify other models, e.g.
# # !ollama pull smollm2

# %%
query = "What is the dress code for major exams according to the handbook?"

# %% [markdown]
# ### No Context
# 
# Similar to earlier, let's start with the No Context approach.
# 
# The No Context approach relies entirely on the pre-trained internal memory of the LLM. As discussed earlier, the model answers questions based solely on data it digested up until its training cutoff.
# 
# This method is incredibly fast and inexpensive because the prompt payload is tiny. However, it is highly prone to confident hallucinations or flat refusals when asked about real-time events, private data, or niche corporate knowledge.

# %%
from langchain_community.llms import Ollama
llm = Ollama(model="gemma3:1b")

# 1. Reuse the exact same query and LLM instance from before
naive_query = query

# 2. Define a simple prompt that asks the question directly
naive_prompt_template = ChatPromptTemplate.from_template("""
You are an AI assistant. Answer the user's question to the best of your ability.

USER QUESTION:
{question}

ANSWER:
""")

print(f"Sending the query directly to the LLM WITHOUT any database context...\n")

# 3. Set up the direct chain
naive_chain = naive_prompt_template | llm | StrOutputParser()

# 4. Execute the chain
naive_response = naive_chain.invoke({
    "question": naive_query
})

print("--- Final AI Response (WITHOUT Context) ---")
print(naive_response)

# %% [markdown]
# ### Full Context
# The Full Context method, often called "context stuffing," bypasses databases entirely by pasting raw, un-chunked source documents directly into the prompt alongside the user's question.
# 
# Expect near-perfect factual accuracy for shorter files. However, as the document grows and starts pushing past the expected context window, the model's attention degrades rapidly. You will notice a sharp spike in hallucinations, missed details ("lost in the middle"), or outright model failure as it overflows its memory capacity.
# 
# Another downside is a major bottleneck in production: soaring token costs, high latency, and hard context window crashes when files scale up.

# %%
# 1. Reuse the exact same query and LLM instance
full_context_query = query

# 2. Re-read or reference your completely un-chunked, raw original text
raw_document_context = docs_pdf

# 3. Reuse our strict RAG prompt template from Step 7
print("Sending the ENTIRE document to the LLM at once (This may take longer)...")

# Execute the same pipeline
full_context_chain = prompt_template | llm | StrOutputParser()

import time
start_time = time.time()

full_context_response = full_context_chain.invoke({
    "context": raw_document_context,
    "question": full_context_query
})

end_time = time.time()
print(f"Done! Generation took {end_time - start_time:.2f} seconds.")

print("\n--- Final AI Response (With FULL Document) ---")
print(full_context_response)

# %% [markdown]
# ### Using RAG
# 
# The RAG architecture balances accuracy and efficiency. It converts documents into searchable semantic chunks, queries a vector database to extract only the most relevant snippets, and feeds just those specific pieces to the LLM.
# 
# This is the production standard for large datasets. It keeps costs and latency low while maintaining accuracy. However, its success depends entirely on your chunking strategy; poor retrieval will directly cause the model to generate incomplete or wrong answers.

# %%
from langchain_community.llms import Ollama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# 1. Initialize our local generative model via Ollama
print("Initializing Ollama LLM for generation...")
llm = Ollama(model="gemma3:1b")

# 2. Define the prompt template that stitches the context and question together
# This template acts as a strict guardrail for the AI's behavior.
prompt_template = ChatPromptTemplate.from_template("""
You are a helpful, factual AI assistant. Your task is to answer the user's question using ONLY the provided context.
If the context does not contain the answer, cleanly state that you do not know. Do not make up answers.

---
RETRIEVED CONTEXT FROM DATABASE:
{context}

---
USER QUESTION:
{question}

ANSWER:
""")

# 3. Pull the EXACT query and output from our previous retrieval cell
# We extract the text content from each LangChain document and join them together.
user_query = query
retrieved_context = "\n\n".join([doc.page_content for doc in mmr_results])

# 4. Format the prompt and send it to the LLM
print(f"\nSending context and query to the LLM...\n")

# Chain components together using LangChain Expression Language (LCEL)
rag_chain = prompt_template | llm | StrOutputParser()

# Execute the chain
response = rag_chain.invoke({
    "context": retrieved_context,
    "question": user_query
})

print("--- Query ---")
print(user_query)

print("--- Context ---")
print(retrieved_context)

print("--- Final AI Response ---")
print(response)

# %% [markdown]
# ### [EXERCISE] Try other queries and compare the output with full context, with RAG, and without context.
# 
# Test different types of questions across all three methods. Fill out the matrix below in your notes to evaluate the trade-offs:
# 
# | Metric | No Context | Full Context | RAG |
# | :--- | :--- | :--- | :--- |
# | **Speed / Latency** | Fast ⚡ | Slow 🐢 | Moderate ⚖️ |
# | **Hallucination Risk** | High | Low | Low-Medium (Depends on chunking) |
# | **Handling Outdated Info**| Poor | Excellent | Excellent |
# | **System Complexity** | None | Low | High (Requires DB & Embeddings) |

# %%
# Setup
full_text = "\n\n".join([doc.page_content for doc in documents])
naive_chain = prompt_template | llm | StrOutputParser()

# No Context (Naive)
naive_response = naive_chain.invoke({"question": user_query, "context": "None"})

# Full Context
full_context_response = naive_chain.invoke({"question": user_query, "context": full_text})

# RAG
rag_response = response

print(f"Query: {user_query}\n")
print(f"No Context: {naive_response}\n")
print(f"Full Context: {full_context_response}\n")
print(f"RAG: {rag_response}\n")

# %% [markdown]
# ## Section 11. University FAQ bot

# %% [markdown]
# Prototype a **University FAQ Bot** that answers student questions from the student handbook
# 
# **What we want**:
# 
# - Semantic Context Matching: The system must locate the correct policy chunk even if the student uses casual language (e.g., matching "flunking out" to "Academic Dismissal").
# 
# - Strict Grounding Guardrails: The LLM must rely only on the provided handbook text to prevent hallucination. If a policy is missing from the source text, it must explicitly state its lack of information rather than guessing.
# 
# - Source Attribution: The output must cite the exact document section and page number so the student can verify the official rule.
# 
# 
# Sample user input:
# ```
# Hey, I had a family emergency and completely missed my physics midterm yesterday. Am I going to get a zero or can I take a makeup test?
# ```
# 
# Sample Grounding Sources:
# ```
# [Source: Student_Handbook_2026.pdf | Section 4.2: Examination Absences | Page 14]
# "Absences from scheduled midterms or final examinations are classified as either Excused or Unexcused. Unexcused absences automatically result in a grade of 0.0 for the respective evaluation. Excused absences are granted only under extreme, documented circumstances (e.g., medical emergencies, severe family crises). To secure an excused absence, the student must submit an Official Absence Petition alongside verifiable documentation to the Office of Student Affairs within forty-eight (48) hours of the missed examination period. Upon administrative approval, the student is permitted to sit for a rescheduled makeup examination, which must be completed within 7 calendar days of the original test date."
# 
# [Source: Student_Handbook_2026.pdf | Section 4.5: Academic Grievances | Page 16]
# "Students wishing to appeal an academic grade or an unexcused exam absence penalty must initiate a formal appeal with the Department Chair no later than five (5) business days following the posting of the contested grade."
# ```
# 
# Sample LLM Output:
# ```
# Based on the Student Handbook (Section 4.2, Page 14), you will not automatically receive a zero, provided you submit official documentation.
# 
# Here are the specific steps you must follow:
# 1. You must submit an Official Absence Petition along with verified documentation of your family emergency to the Office of Student Affairs.
# 2. This petition must be filed within forty-eight (48) hours of the missed exam.
# 3. If approved, you will be granted a excused absence, and you must coordinate with your physics professor to take a rescheduled makeup exam within 7 calendar days.
# 
# If you fail to submit the petition within the 48-hour window, the absence will remain unexcused, and a grade of 0.0 will be recorded for that midterm.
# 
# ```

# %%
from langchain_community.llms import Ollama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Configure MMR retriever on existing Chroma db
retriever = db.as_retriever(
    search_type="mmr",
    search_kwargs={"k": 5, "fetch_k": 15}
)

# System prompt to prevent hallucinations
faq_prompt = ChatPromptTemplate.from_template("""
You are a factual University Student Handbook assistant.
Answer the student's question clearly, using the provided context below.

IF the answer cannot be found in the context,
DO: Respond EXACTLY with: "Apologies, that information is not currently available within the student handbook."

IMPORTANT: Do NOT make up, guess, infer, or invent information. Base your response solely on the text provided.

---
RETRIEVED CONTEXT FROM THE STUDENT HANDBOOK
{context}

---
USER/STUDENT'S QUESTION
{question}

ANSWER:
""")

llm = Ollama(model="gemma3:1b")

def format_sources(docs: list) -> str:
    citations = []
    for i, doc in enumerate(docs):
        page = doc.metadata.get("page_label", doc.metadata.get("page", "N/A"))
        source = doc.metadata.get("source", "Student Handbook")
        citations.append(f"  [{i+1}] {source} | Page {page}")
    return "\n".join(citations)

def ask_bot(question: str) -> None:
    # Retrieve -> Assemble -> Generate -> Cite
    retrieved_docs = retriever.invoke(question)
    assembled_context = "\n\n".join([doc.page_content for doc in retrieved_docs])

    rag_chain = faq_prompt | llm | StrOutputParser()
    answer = rag_chain.invoke({"context": assembled_context, "question": question})

    print("=" * 65)
    print(f"STUDENT QUESTION:\n  {question}\n")
    print("HANDBOOK ANSWER:")
    print(answer)
    print("\nGROUNDING SOURCES:")
    print(format_sources(retrieved_docs))
    print("=" * 65)

print("[University FAQ Bot system now running...]")

# %%
# In-context question
ask_bot("If I get an 88% on my final exam, what letter grade does that correspond to?")

print()

# Out-of-scope question
ask_bot("Is there a parking lot in the university? What are the rates, and is there an overnight fee?")

# %% [markdown]
# ### [EXERCISE] Improving the Student Handbook RAG Pipeline
# 
# In this exercise, you will act as an AI QA Engineer. Your goal is to tweak, break, and optimize the **Retrieval-Augmented Generation (RAG)** pipeline you just built for the University Student Handbook FAQ Bot.
# 
# Instead of treating the pipeline as a "black box," you will modify parameters at every stage of the lifecycle to observe how your architectural choices change the accuracy, cost, and safety of the final answers.
# 
# ---
# 
# ### **The RAG Pipeline Checklist**
# 
# #### **1. Ingest**
# - [ ] **Loaders:** Toggle between loading data from a static document (`PyPDFLoader`) versus a dynamic web page (`WebBaseLoader`). Observe if formatting changes affect text extraction.
# 
# #### **2. Chunk**
# - [ ] **Chunk Size & Overlap:** Experiment with splitting your text into very small pieces (e.g., 200 characters) versus massive pieces (e.g., 2,000 characters).
# 
# #### **3. Embed**
# - [ ] **Dimensions & Latency:** Compare a local open-source model against a cloud API model. Track how fast they convert your text into math coordinates.
# 
# #### **4. Store**
# - [ ] **DB Initialization:** Ensure your database is correctly caching your vectors locally on disk so you don't re-embed data on every notebook run.
# 
# #### **5. Retrieve**
# - [ ] **Search Methods:** Swap between standard **Similarity Search (Top-$K$)** and **Maximum Marginal Relevance (MMR)**.
# - [ ] **$K$-Value:** Change your `k` parameter (the number of chunks retrieved) from $K=1$ to $K=5$. See if adding more pages helps or just adds confusing noise.
# 
# #### **6. Generate Response**
# - [ ] **Guardrails:** Test a loose prompt versus a strict **Grounded Prompt** (e.g., *"If the context does not explicitly mention the answer, reply with 'Data Not Found'"*).
# - [ ] **Model Temperature:** Change your model's temperature from `0.0` (strict fact extraction) to `1.0` (creative phrasing) and watch for hallucinations.
# 
# ---
# 
# ### **7. Run Multiple Experiments**
# 
# Run the cells in your notebook using these two tricky student questions designed to stress-test your system:
# * **The Normal Question:** *"What happens if I miss an exam because of a family emergency?"* (This info should exist in the handbook).
# * **The Out-of-Bounds Question:** *"Where can I buy a parking pass for the campus garage?"* (Assuming parking rules are completely missing from the handbook).
# 
# #### **Example Experiment Logs to Replicate:**
# * **Experiment A (Loose Setup):** Basic Similarity ($K=1$), Temperature = $0.9$.
#   * *Result:* The bot completely hallucinates a fake rule about campus parking passes because it guessed.
# * **Experiment B (Production Setup):** MMR Search ($K=3$), Temperature = $0.0$, Strict Grounding Prompt.
#   * *Result:* The bot correctly stops itself and states: *"I cannot find information regarding parking passes in the provided handbook segments."*
# 
# ---
# 
# ### **8. Note Down Your Observations, Analysis, and Conclusions**
# 
# Add a markdown cell and answer the following:
# 
# 1. **What worked?** Did changing the retrieval method to MMR or adjusting the $K$-value make your answers more complete?
# 2. **What went wrong?** Show an example of an experiment where the bot hallucinated or cut off a policy answer midway through execution. Why did it happen?
# 3. **Your Final Settings:** Based on your testing, what are the perfect settings (Chunk Size, Retrieval Type, $K$-value, and Temperature) to deploy a safe, zero-hallucination FAQ Bot for your university?

# %%
# INGEST
from langchain_community.document_loaders import PyPDFLoader, WebBaseLoader

# Static document loader
loader_pdf = PyPDFLoader("/content/student_handbook.pdf")
docs_pdf = loader_pdf.load()
print(f"PDF Loader: {len(docs_pdf)} pages loaded")

# Dynamic web page loader
loader_web = WebBaseLoader("https://drive.google.com/uc?export=download&id=18w-vzTxTPp7ao70MWCU0_kWDe7Df8yxv")
docs_web = loader_web.load()
print(f"Web Loader: {len(docs_web)} documents loaded")

# Observe formatting differences
print("\n--- PDF Sample ---")
print(docs_pdf[0].page_content[:300])
print("\n--- Web Sample ---")
print(docs_web[0].page_content[:300])

# %%
# CHUNK
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Small chunks
small_splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=20)
small_chunks = small_splitter.split_documents(docs_pdf)
print(f"Small chunks (200): {len(small_chunks)} chunks")

# Large chunks
large_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
large_chunks = large_splitter.split_documents(docs_pdf)
print(f"Large chunks (2000): {len(large_chunks)} chunks")

# Review the size difference
print("\n--- Small Chunk Sample ---")
print(small_chunks[0].page_content.strip())
print("\n--- Large Chunk Sample ---")
print(large_chunks[0].page_content.strip())

# %%
# for below code block
!pip install -q langchain-huggingface

# %%
import time
from langchain_ollama import OllamaEmbeddings
from langchain_huggingface import HuggingFaceEmbeddings

# Sample texts for testing
sample_texts = [chunk.page_content for chunk in small_chunks[:10]]

# Local model (Ollama nomic-embed-text)
print("Loading Ollama model...")
local_embeddings = OllamaEmbeddings(model="nomic-embed-text")
start = time.time()
local_vecs = local_embeddings.embed_documents(sample_texts)
local_time = time.time() - start
print(f"Ollama | Dimensions: {len(local_vecs[0])} | Latency: {local_time:.2f}s")

# Cloud model (HuggingFace: All-MiniLM-L6-v2)
print("\nLoading Hugging Face model...")
hf_embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
start = time.time()
hf_vecs = hf_embeddings.embed_documents(sample_texts)
hf_time = time.time() - start
print(f"HuggingFace | Dimensions: {len(hf_vecs[0])} | Latency: {hf_time:.2f}s")

# %%
# STORE
from langchain_chroma import Chroma

PERSIST_DIR = "./chroma_handbook_db"

# Build and persist on first run
db = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings_model,
    persist_directory=PERSIST_DIR
)
print(f"Database persisted to: {PERSIST_DIR}")

# Load from disk on later runs
db = Chroma(
    persist_directory=PERSIST_DIR,
    embedding_function=embeddings_model
)
print(f"Database loaded from disk: {db._collection.count()} vectors ready")

# %%
# RETRIEVE
test_query = "What happens if I miss an exam because of a family emergency?"

# Top-K Similarity Search
for k in [1, 3, 5]:
    results = db.similarity_search(test_query, k=k)
    print(f"\n--- Similarity Search | k={k} ---")
    for i, doc in enumerate(results):
        print(f"  Chunk {i+1}: {doc.page_content[:100].strip()}...")

# MMR Search
for k in [1, 3, 5]:
    results = db.max_marginal_relevance_search(test_query, k=k, fetch_k=10)
    print(f"\n--- MMR Search | k={k} ---")
    for i, doc in enumerate(results):
        print(f"  Chunk {i+1}: {doc.page_content[:100].strip()}...")

# %%
# GENERATE RESPONSE
from langchain_community.llms import Ollama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

loose_prompt = ChatPromptTemplate.from_template("""
You are a helpful assistant. Answer the question as best you can.

CONTEXT: {context}
QUESTION: {question}
ANSWER:
""")

strict_prompt = ChatPromptTemplate.from_template("""
You are a strict University Student Handbook assistant.
Answer using ONLY the context below. If the answer is not present, respond with:
"I don't know. That information is not available in the provided handbook sections."
Do NOT guess or infer.

CONTEXT: {context}
QUESTION: {question}
ANSWER:
""")

context = "\n\n".join([doc.page_content for doc in db.similarity_search(test_query, k=3)])

for temp in [0.0, 1.0]:
    for label, prompt in [("Loose", loose_prompt), ("Strict", strict_prompt)]:
        llm = Ollama(model="gemma3:1b", temperature=temp)
        chain = prompt | llm | StrOutputParser()
        response = chain.invoke({"context": context, "question": test_query})
        print(f"\n--- {label} Prompt | Temperature={temp} ---")
        print(response)

# %% [markdown]
# ## Section 12. Completion Checklist
# To ensure you haven't missed anything, mark the following checkboxes:
# 
# - [X] **LLM Limitations**
#   - [X] Knowledge boundary demo
#   - [X] Hallucination demo
# 
# - [X] **Document Ingestion**
#   - [X] Unstructured Documents (PDFs)
#   - [X] Web Scraping (URLs)
# 
# - [X] **Naive / Keyword Search**
#   - [X] Keyword extraction & block scanning
#   - [X] Synonym failure case
# 
# - [X] **Cosine Similarity**
#   - [X] Word-pair similarity
#   - [X] Sentence-level similarity
# 
# - [X] **Chunking Strategies**
#   - [X] Fixed-Size
#   - [X] Sentence-Based / Header-Based
#   - [X] Semantic Chunking
# 
# - [X] **Embedding Models**
# 
# - [X] **Vector Storage**
# 
# - [X] **Advanced Information Retrieval**
#   - [X] Similarity Search
#   - [X] Top-K Selection
#   - [X] Maximum Marginal Relevance (MMR)
#   - [X] Context Window Retrieval
# 
# - [X] **Generation**
# 
# - [X] **University FAQ bot Use-Case**
#   - [X] Ingest
#   - [X] Chunk
#   - [X] Embed
#   - [X] Store
#   - [X] Retrieve
#   - [X] Generate Response
#   - [X] Run multiple experiments
#   - [X] Note down your observations, analysis and conclusions
# 


