# %% [markdown]
# # **IMPORTANT:** Please DO NOT edit this file directly. Save your own copy and open that in Colab (see more below).

# %% [markdown]
# # Week 1: Prompt Engineering
# 
# ## Getting Started
# This is a Jupyter notebook. Download this .ipynb file locally/save a copy in your personal Google Drive account.
# 
# You can run these in two ways.
# 
# <br>
# 
# **Option 1: Google Colab**
# 
# *This is recommended, but sessions may disconnect after some time.*
# 
# *On the upper right, try to get `Change runtime type > T4 GPU` (if it's available) for GPU-enabled inference, instead of just `CPU`.*
# 
# Go to https://colab.research.google.com/
# 
# Click `File > Open notebook > Upload`  
# (Alternatively, click `File > Open notebook > Google Drive`)
# 
# <br>
# 
# **Option 2: Run the notebook locally**
# 
# In a Terminal with Python installed, run `pip install notebook`.
# 
# Then in the directory where the file was downloaded, run `jupyter notebook`.
# 
# <br>
# 
# ## Running a Cell
# To run a cell, click the Play button. (Or use Ctrl+Enter / Cmd+Enter)
# 
# - Code cells are generally in Python
# - Lines prefixed with `!` are shell commands (e.g. `!pip install`)
# - Text cells support Markdown formatting
# 
# On the toolbar to the left, you can view the Table of Contents and also run a specific section at once.

# %% [markdown]
# # Section 1. Hello World: Getting Your First LLM Response
# 

# %% [markdown]
# ## 1.1 (Optional) Using Proprietary LLM APIs like ChatGPT or Gemini
# If you have an API key for ChatGPT (or Gemini), you can try using it. Otherwise, skip to Section 1.2.

# %%
# See https://developers.openai.com/api/docs for more details.
# Set the environment variable for the OpenAI API key.

# Using `%env` in Google Colab is similar to using `export ENV_KEY=env_value` in the terminal.
# IMPORTANT: Keep API keys private, do not share them publicly or commit them to Git repositories.
# Environment variables are used so that you do not hardcode API keys in code.
# If using Google Colab, also check out Google Colab Secrets.

# Uncomment the following line if you have an API key
# %env OPENAI_API_KEY=sk-yourapikey

# %%
# Uncomment the following lines if you have an API key set.
# from openai import OpenAI
# client = OpenAI()

# response = client.responses.create(
#     model="gpt-5.5",
#     input="Write a short bedtime story about a unicorn."
# )

# print(response.output_text)

# %% [markdown]
# ## 1.2 Using Ollama
# 
# As default, we'll be using open-source LLMs using Ollama.

# %% [markdown]
# ### 1.2.1 Ollama Setup

# %%
# This is one way to check for GPU availability
!nvidia-smi

# %%
!sudo apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh
!pip install ollama

# %%
import subprocess, time
subprocess.Popen(["ollama", "serve"])
time.sleep(5)

# %%
!ollama pull gemma3:1b

# Or specify other models, e.g.
# # !ollama pull smollm2

# %%
# Select specific model here
model = "gemma3:1b"

# %%
from ollama import chat

response = chat(
    model = model,
    messages = [{"role": "user", 'content': "What can you help me with?"}]
)

print(response.message.content)

# %%
# May take 2-3 mins on first run, copied for reference
# from ollama import chat

# response = chat(
#     model = model,
#     messages = [{"role": "user", 'content': "What can you help me with?"}]
# )

# print(response.message.content)

# %%
def ChatWrapper(user_prompt: str, system_prompt: str = "", model: str="gemma3:1b", options={}):
  print("="*72)
  print("System Prompt:")
  print(system_prompt)
  print()
  print("User Input:\n", user_prompt)
  llm_response = chat(
      model = model,
      messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}],
      options = options
  ).message.content
  print()
  print("LLM Response:\n", llm_response)
  print("="*72)

# %%
ChatWrapper(
    user_prompt = "Create a haiku about programming",
    options = {"top_k": 5},
    model="gemma3:1b"
)

# %% [markdown]
# ### 1.2.2 [EXERCISE] Prompting and Sampling
# Now it's your turn!
# 
# Try out variations of the following:
# - [X] User Prompt
# - [X] System Prompt
# - [X] Temperature
# - [X] Top-K
# - [X] Top-P
# - [X] Max Tokens
# - [X] Mark all the checkboxes above with "X" when you completed them

# %%
# YOUR CODE HERE
# Leave the cell output as is after you run, do not clear the cell output
# TIP: Search for the API/Ollama docs for specifying sampling parameters

# %%
# Childlike | High temp | Short response | Limited vocabulary
ChatWrapper(
    user_prompt="Explain why the sky is blue",
    system_prompt="You are a child. When asked about why the sky is blue, do not answer it in an intellectual manner. Simply answer it like a child would.",
    options={"temparature": 1.5, "num_predict": 29, 'top_k': 25, 'top_p': 1}

)

# %%
# Intellectual | Low temp | Lengthy response | Wide vocabulary
ChatWrapper(
    user_prompt="Explain a particle accelerator like I'm in grad school",
    system_prompt="You are a doctor in quantum mechanics and applied physics. Explain the topics in a concise, but intellectual way. Limit your answers to around 3 sentences max.",
    options={"temparature": 0.3, "num_predict": 150, 'top_k': 200, 'top_p': 0.4}
)


# %% [markdown]
# # Section 2. Three Common LLM Tasks
# 
# We have the folowing LLM Tasks:
#  - Classification
#  - Summarization
#  - Extraction
# 
# For each task, we will explore Prompt Engineering techniques that we can apply to improve the responses from our LLMs.
# 

# %% [markdown]
# ## 2.1 Classification
# 
# For classification, we will explore the following techniques.
# 
# | Technique | Description | Use Case |
# | --------- | ----------- | -------- |
# | Zero-shot | Query the LLM without giving examples | For simple or general tasks; lower token usage |
# | Few-shot  | Provide 2-5 examples to LLM | For expecting strict input/output formats |
# | CoT       | Instruct it to reason step-by-step | For complex tasks; reduces hallucination |
# | Role-based| Instruct it to answer with a persona | Used for setting conversational tone |

# %% [markdown]
# ### 2.1.1 Zero-shot Classification
# 
# If you try running the following multiple times, you will see that the answer sometimes changes drastically.
# 

# %%
ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = "Classify this review as positive, negative, or neutral",
  model="gemma3:1b"
)
print()

ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = "Classify as bad, good, or neutral",
  model="gemma3:1b"
)
print()

ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = "Classify as happy, sad, or angry",
  model="gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Zero-shot Classification
# 
# Experiment and try out examples of zero-shot classification.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
    system_prompt="Classify the following as happy, sad, angry, or neutral.",
    user_prompt="1. Darn it!  2. Let's go!  3. Nice.  4. Nice!  5. No!"
)


# %%
ChatWrapper(
    system_prompt="Classify the following as happy, sad, angry, or neutral.",
    user_prompt="1. I love you, but it hurts. 2. Stop! 3. Say that again. 4. Are you kidding me? 5. Wow! You're so good at this!"
)


# %% [markdown]
# ### 2.1.2 Few-shot Classification
# 
# With few-shot prompting, we provide a couple of examples to more strictly define the desired input/output patterns.
# 
# Observe how the Output only contains "Positive", "Negative", or "Neutral", without additional explanations.

# %%
# Here is an example of using Few-shot Classification

ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Example:
    ```
    Input:
      I love this item that I bought
    Output:
      Positive
    ```

    ```
    Input:
      I hate this item that I bought. It broke down.
    Output:
      Negative
    ```

    ```
    Input:
      This item is okay. It is good enough for its price.
    Output:
      Neutral
    ```
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# Now, let's try giving examples where there's an additional reasoning in the expected output.

# %%

ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Example:
    ```
    Input:
      I love this item that I bought
    Output:
      Positive - because the user said it loves the item
    ```

    ```
    Input:
      I hate this item that I bought. It broke down.
    Output:
      Negative - because it broke down and user hates the item
    ```
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Few-shot Classification
# 
# Experiment and try out exammples of few-shot classification.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
    system_prompt="""

    Determine if the following statements are genuine or passive aggressive.

    Example:
    ```
    Input: I love how you don't care about your appearance.

    Output: Passive aggressive - contains backhanded compliment

    ```

    ```
    Input: I appreciate the work you've done so far.

    Output: Genuine - no signs of hostility, denial or criticism

    ```

    ```
    Input: I wish I could relax and ignore the mess like you do.

    Output: Passive aggressive - contains indirect complaint

    ```

    ```
    Input: You look stunning tonight!

    Output: Genuine - no backhanded compliments with the given context

    ```

    """,

    user_prompt="It's fascinating how you always find a way to make this about you."
)

# %% [markdown]
# ### 2.1.3 Chain-of-Thought (CoT)
# 
# For chain-of-thought prompting, we instruct the LLM to break down its step-by-step reasoning while answering.
# 
# This is analogous to expecting full solutions in an exam (instead of just jumping straight to the final answer), and can help reduce hallucination.

# %%
ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Reason out your answer step-by-step.
    You need to first identify sentiment words then apply their weights.
    The final step is to classify the overall user sentiment to positive, negative, or neutral.
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# Let's try another example.

# %%
ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I don't mind. For the price point, I think it's fair and it did work.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Reason out your answer step-by-step.
    You need to first identify sentiment words then apply their weights.
    The final step is to classify the overall user sentiment to positive, negative, or neutral.
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] CoT Classification
# 
# Experiment and try out exammples of CoT classification.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "Oh, I'm surprised you actually remembered.",
  system_prompt = """
    Determine if the given statements are genuine or passive-aggressive.
    First, identify any hidden criticisms, backhanded compliments, complaints, or frustrations.
    Second, reason out why the statement would be either genuine or passive-aggressive.
    Third, identify sentiment words and apply their weights
    Lastly, classify the entire statement as either genuine or passive-aggressive.

    """,
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.1.4 Role-based
# 
# This involves defining a persona for your LLM, and is useful for setting conversational tone.

# %%
ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Act as a senior data analyst.
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# Now, let's try having it act as a customer.

# %%
ChatWrapper(
  user_prompt = "This vacuum looks good at first but broke after 3 weeks, I hate it.",
  system_prompt = """
    Classify this review as positive, negative, or neutral.
    Act as a fellow consumer and judge wether you would buy the item or not
    """,
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Role-based Classification
# 
# Experiment and try out exammples of Role-based classification.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "Must be nice having everything handed to you.",
  system_prompt = """
    You are an expert CIA detective and can read in between the lines.
    Classify the following statement as either genuine or passive-aggressive.
    """,
  model = "gemma3:1b"
)


# %% [markdown]
# ## 2.2 Summarization
# 
# Summarization is a common task in Natural Language Processing. This can be used to simplify large amounts of text for human consumption, but modern Agentic Systems can also summarize the output of one agent and feed it as input to another agent.
# 
# We will be talking about 4 main summarization strategies.
#  - Basic Summarization
#  - Constrained Summarization
#  - Chain-of-Thought Summarization
#  - Role-based Summarization

# %% [markdown]
# ### 2.2.1 Basic Summarization
# 
# We basically just do a simple system prompt for the LLM and directly tell it to summarize.

# %%
ChatWrapper(
  user_prompt = """
  - This machine has more pull than a politician during election season.
  - Finally, a vacuum that sucks at its job in the best way possible.
  - It’s so quiet I actually had to check if it was still turned on.
  - Sleek, powerful, and makes me feel significantly more like a functional adult.
  - It cleans the floors well enough, provided you aren't expecting a miracle.
  - The battery life is decent, though it won't be winning any endurance awards.
  - It’s a standard vacuum that does exactly what it says on the box, nothing more.
  - I’ve seen more suction power from a cheap straw in a thick milkshake.
  """,
  system_prompt = "Summarize the reviews into one sentence",
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Basic Summarization
# 
# Experiment and try out exammples of Basic Summarization.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = """
  AlexandreNGamR responded to a tweet about the State of Play by saying this:

It’s the Faye game.

There’s a rumor from at least last March that the next big game directed by Santa Monica Studio director Cory Barlog is a God of War spinoff starring Kratos’ second wife, Faye, AKA the mythological Frost giant Laufey.

MP1st has added fuel to the fire on this rumored game. They claim it will actually explore multiple mythologies, naming Chinese, Japanese, and Maya myths.

This could actually account for why two sources made opposing claims on how exciting this State of Play is. The idea of the game already seems to be divisive. Of course, we can’t know how good the game will actually be until the final reviews come out.

At least, the fans are looking forward to another PlayStation 5 first-party exclusive, so we’ll see if they get that next week.
  """,
  system_prompt = "Summarize the body of text in two sentences.",
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.2.2 Constrained Summarization
# 
# This is when we add restrictions to focus on the key points that we care about more, or want to limit how much the LLM responds.

# %%
ChatWrapper(
  user_prompt = """
  - This machine has more pull than a politician during election season.
  - Finally, a vacuum that sucks at its job in the best way possible.
  - It’s so quiet I actually had to check if it was still turned on.
  - Sleek, powerful, and makes me feel significantly more like a functional adult.
  - It cleans the floors well enough, provided you aren't expecting a miracle.
  - The battery life is decent, though it won't be winning any endurance awards.
  - It’s a standard vacuum that does exactly what it says on the box, nothing more.
  - I’ve seen more suction power from a cheap straw in a thick milkshake.
  """,
  system_prompt = "Summarize the reviews. One short sentence for the general user experience and another short sentence for the physical limitations.",
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Constrained Summarization
# 
# Experiment and try out exammples of Constrained Summarization.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = """
  AlexandreNGamR responded to a tweet about the State of Play by saying this:

It’s the Faye game.

There’s a rumor from at least last March that the next big game directed by Santa Monica Studio director Cory Barlog is a God of War spinoff starring Kratos’ second wife, Faye, AKA the mythological Frost giant Laufey.

MP1st has added fuel to the fire on this rumored game. They claim it will actually explore multiple mythologies, naming Chinese, Japanese, and Maya myths.

This could actually account for why two sources made opposing claims on how exciting this State of Play is. The idea of the game already seems to be divisive. Of course, we can’t know how good the game will actually be until the final reviews come out.

At least, the fans are looking forward to another PlayStation 5 first-party exclusive, so we’ll see if they get that next week.
  """,
  system_prompt = "Summarize the body of text into three short (each less than 10 words) sentences: first sentence for the actual content, second for the additional details, and third for the future implications. Output all into one continuous paragraph. Limit to 3 sentences maximum.",
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.2.3 Chain-of-Thought Summarization
# 
# This is when we want a more detailed summarization, using more transparent reasoning. This approach is helpful for more complex tasks.

# %%
ChatWrapper(
  user_prompt = """
  - This machine has more pull than a politician during election season.
  - Finally, a vacuum that sucks at its job in the best way possible.
  - It’s so quiet I actually had to check if it was still turned on.
  - Sleek, powerful, and makes me feel significantly more like a functional adult.
  - It cleans the floors well enough, provided you aren't expecting a miracle.
  - The battery life is decent, though it won't be winning any endurance awards.
  - It’s a standard vacuum that does exactly what it says on the box, nothing more.
  - I’ve seen more suction power from a cheap straw in a thick milkshake.
  """,
  system_prompt = "Summarize the reviews. Have a short 3-step reasoning.",
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Chain-of-Thought Summarization
# 
# Experiment and try out exammples of Chain-of-Thought Summarization.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output
ChatWrapper(
  user_prompt = """
  AlexandreNGamR responded to a tweet about the State of Play by saying this:

It’s the Faye game.

There’s a rumor from at least last March that the next big game directed by Santa Monica Studio director Cory Barlog is a God of War spinoff starring Kratos’ second wife, Faye, AKA the mythological Frost giant Laufey.

MP1st has added fuel to the fire on this rumored game. They claim it will actually explore multiple mythologies, naming Chinese, Japanese, and Maya myths.

This could actually account for why two sources made opposing claims on how exciting this State of Play is. The idea of the game already seems to be divisive. Of course, we can’t know how good the game will actually be until the final reviews come out.

At least, the fans are looking forward to another PlayStation 5 first-party exclusive, so we’ll see if they get that next week.
  """,
  system_prompt = "Summarize the body of text, use 5-step reasoning in your summarization.",
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.2.4 Role-based Summarization
# 
# Providing a persona sets the conversational tone used by the LLM as it summarizes the user's input.

# %%
ChatWrapper(
  user_prompt = """
  - This machine has more pull than a politician during election season.
  - Finally, a vacuum that sucks at its job in the best way possible.
  - It’s so quiet I actually had to check if it was still turned on.
  - Sleek, powerful, and makes me feel significantly more like a functional adult.
  - It cleans the floors well enough, provided you aren't expecting a miracle.
  - The battery life is decent, though it won't be winning any endurance awards.
  - It’s a standard vacuum that does exactly what it says on the box, nothing more.
  - I’ve seen more suction power from a cheap straw in a thick milkshake.
  """,
  system_prompt = "You are a reseller of the product. Summarize the reviews and assess fit for reselling. Make it very short.",
  options = {},
  model = "gemma3:1b"
)

# %% [markdown]
# Let's try again with max tokens (`num_predict`)

# %%
ChatWrapper(
  user_prompt = """
  - This machine has more pull than a politician during election season.
  - Finally, a vacuum that sucks at its job in the best way possible.
  - It’s so quiet I actually had to check if it was still turned on.
  - Sleek, powerful, and makes me feel significantly more like a functional adult.
  - It cleans the floors well enough, provided you aren't expecting a miracle.
  - The battery life is decent, though it won't be winning any endurance awards.
  - It’s a standard vacuum that does exactly what it says on the box, nothing more.
  - I’ve seen more suction power from a cheap straw in a thick milkshake.
  """,
  system_prompt = "You are a reseller of the product. Summarize the reviews and assess fit for reselling. Make it very short.",
  options = {'num_predict': 100},
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Role-based Summarization
# 
# Experiment and try out exammples of Role-based Summarization.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = """
  AlexandreNGamR responded to a tweet about the State of Play by saying this:

It’s the Faye game.

There’s a rumor from at least last March that the next big game directed by Santa Monica Studio director Cory Barlog is a God of War spinoff starring Kratos’ second wife, Faye, AKA the mythological Frost giant Laufey.

MP1st has added fuel to the fire on this rumored game. They claim it will actually explore multiple mythologies, naming Chinese, Japanese, and Maya myths.

This could actually account for why two sources made opposing claims on how exciting this State of Play is. The idea of the game already seems to be divisive. Of course, we can’t know how good the game will actually be until the final reviews come out.

At least, the fans are looking forward to another PlayStation 5 first-party exclusive, so we’ll see if they get that next week.
  """,
  system_prompt = "You are a gamer nerd and are up to date with the news. Summarize the piece of information and quickly explain like I'm a normie.",
  options = {'num_predict': 200},
  model = "gemma3:1b"
)

# %% [markdown]
# ## 2.3 Extraction
# 
# Extraction comes into play when we use the LLM to identify and retrieve important information from the input text. This helps in readability, and more importantly is needed for reliably passing data downstream into APIs, function calls, or sub-agents.
# 
# More specifically, we will be discussing the following strategies:
# - JSON Mode
# - Few-shot
# - Schema
# - Combined

# %% [markdown]
# ### 2.3.1 JSON Mode
# 
# We extract key features from a text and place them inside of a JSON object.

# %%
ChatWrapper(
  user_prompt = "I have been using this CleanPro-5000 vacuum cleaner recently. It broke down after it cleaned up spilled juice.",
  system_prompt = """Based on the user message extract information for the following json
```json
{
  "item": "string",
  "category": "string",
  "issue": "string",
  "time_used": "string",
  "discount_code": "string"
}
```
""",
  options = {'num_predict': 100}, # just to keep it brief
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] JSON Mode
# 
# Experiment and try out exammples of JSON-mode extraction.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "You, me, Saturday night, first week of June 4th 2026, at that night market? Get some 5 dollar hotdogs?",
  system_prompt = """Based on user input extract information for the following json. Strictly follow the data types.
```json
{
  "category": "string",
  "time": "yyyy-mm-dd",
  "place": "string",
  "cuisine": "string",
  "price_range": "string"
}
```
""",
  options = {'num_predict': 100},
  model = "gemma3:1b"
)

# %% [markdown]
# ###  2.3.2 Few-shot JSON Mode
# 
# We can also apply few-shot examples for JSON formatting.

# %%
ChatWrapper(
  user_prompt = "I have been using this CleanPro-5000 vacuum cleaner recently. It broke down after it cleaned up spilled juice.",
  system_prompt = """Based on the user message extract information for the following json
```json
{
  "item": "string",
  "category": "string",
  "issue": "string",
  "time_used": "string",
  "discount_code": "string"
}
```

Consider the following examples:
Example 1:

Input:
“My basketball has holes in it. I have been using it recently. I have no discount code.”
Output:
```json
{
  "item": "basketball",
  "category": "sports",
  "issue": "Holes in basketball",
  "time_used": "recently",
  "discount_code": "absent"
}
```
""",
  options = {'num_predict': 100}, # just to keep it brief
  model = "gemma3:1b"
)

# %% [markdown]
# **TIP**: Popular LLM APIs like ChatGPT also have explicit support for "structured outputs" or "JSON mode".
# 
# See https://developers.openai.com/api/docs/guides/structured-outputs for more details.

# %% [markdown]
# ### [EXERCISE] Few-shot JSON Mode
# 
# Experiment and try out exammples of Few-shot JSON mode (try giving 1-3 examples).
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "You, me, Saturday night, first week of June 4th 2026, at that night market? Get some 100 peso hotdogs?",
  system_prompt = """Based on user input extract information for the following json. Strictly follow the data types.
```json
{
  "topic": "string",
  "category": "string",
  "time": "yyyy-mm-dd",
  "place": "string",
  "price_range": "string"
}
```

Consider the following examples:
Example 1:

Input:
“Meet me at April 2, 2029, at the Shells Dwarf Fight Club. Expect a 300 php entrance fee, this is gonna be lit!”
Output:
```json
{
  "topic": "Fight Club Invitation",
  "category": "Hangout",
  "time": "2029-04-2",
  "place": "Shells Dwarf Fight Club",
  "price_range": "PHP 300"
}
```

""",
  options = {'num_predict': 100},
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.3.3 Schema
# 
# In general, we can define the schema to structure the response: the expected field names, their data type, including any specific ENUM values.
# 
# This need not be JSON, and could be YAML, XML, or other format with a fairly defined structure.

# %%
ChatWrapper(
  user_prompt = "I have been using this CleanPro-5000 vacuum cleaner recently. It broke down after it cleaned up spilled juice.",
  system_prompt = """Extract the following information using the schema below:
```
item: [name of item]
issue: [break|ugly|price]
time: [recent|old]
```
The entries with `|`, you should select from the options there.
""",
  options = {'num_predict': 100}, # just to keep it brief
  model = "gemma3:1b"
)

# %%
# Let's try again with a different user prompt.
ChatWrapper(
  user_prompt = "I have been using this CleanPro-5000 vacuum cleaner recently. It's too pricey.",
  system_prompt = """Extract the following information using the schema below:
```
item: [name of item]
issue: [break|ugly|neither]
time: [recent|old]
```
The entries with `|`, you should select from the exact options there.
""",
  options = {'num_predict': 100}, # just to keep it brief
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Schema
# 
# Experiment and try out exammples of providing a schema. Also note down your observations, esp. on which cases (or models) were compliant vs non-compliant to what you provided.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "You, me, Saturday night, first week of June 4th 2026, at that night market? Buy some 100 peso tshirts on sale!",
  system_prompt = """Extract the following information strictly from the sentence alone, based on the strict schema below.
```
  place: [name of place]
  item: [name of item]
  category: [Casual Event | Work Event]
  price_range: [below 100 | 100-200 | 200-300 | 400+]
```
""",
  options = {'num_predict': 100},
  model = "gemma3:1b"
)

# %% [markdown]
# ### 2.3.4 Combined
# 
# We use JSON mode and provide more details for the schema that we want, esp. when there are edge cases that we need to handle.
# 

# %%
ChatWrapper(
  user_prompt = "I have been using this CleanPro-5000 vacuum cleaner recently. It's too pricey.",
  system_prompt = """Extract the following information using the schema below:
```json
{
  "item": "string" (this should be the item brand),
  "category": "string" (you can only pick between the categories: [work, play]),
  "issue": "string",
  "time_used": "string" (we need exact dates, if the date isn't exact use [undefined]),
  "discount_code": "option" [yes, no]
}
```
""",
  options = {'num_predict': 100}, # just to keep it brief
  model = "gemma3:1b"
)

# %% [markdown]
# ### [EXERCISE] Combined
# 
# Experiment and try out exammples of using JSON mode with a detailed schema. Also note down your observations, esp. on which cases (or models) were compliant vs non-compliant to what you provided.
# 
# - [X] Mark when completed

# %%
# YOUR CODE HERE
# Leave the cell output

ChatWrapper(
  user_prompt = "Meet me at April 2, 2029, at the Shells Dwarf Fight Club. Expect a 300 php entrance fee, this is gonna be lit!",
  system_prompt = """Based on user input extract information for the following json. Strictly follow the data types.
```json
{
  "topic": "string", (nature of event)
  "category": "string", (should be the classification of the event, e.g. [Casual | Career | Formal])
  "time": "yyyy-mm-dd", (follow exact date format [YYYY-MM-DD])
  "place": "string", (name of the place)
  "price_range": "string" (Give a rough minimum cost estimate [PHP 100+ | PHP 1000+ | PHP 5000+])
}
```
""",
  options = {'num_predict': 100},
  model = "gemma3:1b"
)

# %% [markdown]
# ## 3 Customer Support Triage Use Case

# %% [markdown]
# Prototype a customer support agent that triages support tickets according to **urgency** and **category**.
# 
# **What we want**:
# - Limited, exact choices
# - Urgency: `HIGH` / `MEDIUM` / `LOW`
# - Category: finite set (`Billing`, `IT`, etc.)
# - Deterministic output (creative tasks are not needed)
# - Technical, structured formatting (JSON-like with predefined fields)
# - Try experimenting with additional schema fields, e.g. routing to a business department, or confidence score of the classification (see Sample LLM Output below)
# 
# Possible outline of the system prompt (refine this):
# ```
# Classify the following support ticket:
# 
# Few-shot examples:
#   "System down" → Critical/Technical
#   "Refund request" → High/Billing
# 
# Ticket: "{user_input}"
# 
# Classification:
#   Urgency: ___
#   Category: ___
# ```
# 
# Sample user input:
# ```
# I was overcharged $250. I’m on the $49 Pro plan, but got billed $299 for Enterprise. Please refund the difference to my card.
# ```
# 
# Sample LLM Output:
# ```
# {
# "urgency": "high",
# "category": "technical",
# "route": "eng-support",
# "confidence": 0.94
# }
# 
# ```
# 

# %% [markdown]
# ### [EXERCISE] Customer Support Triage
# Showcase how you integrate and experiment with the following components/techniques:
# - [X] system prompt
#   - [X] few shot
#   - [X] structured outputs (using schema definitions / JSON)
#   - [X] chain-of-thought
#   - [X] role-based
# - [X] sampling parameters
#   - [X] temperature
#   - [X] top-k
#   - [X] top-p
#   - [X] max tokens / num_predict
# - [X] Run multiple experiments to showcase consistency (or variation) of LLM responses due to differences in sampling parameters or prompts
# - [X] Note down your observations, analysis and conclusions. (What were followed, what were incorrect, why you picked these prompting techniques based on the use case & what makes sense to actually use based on the results, etc.)

# %%
# YOUR CODE HERE
# Leave the cell output

# TEST 1
ChatWrapper(
    user_prompt="My PHP 17000 refund pushed through, but I have yet to receieve the money despite the system telling me it was delivered. My reference number is RF00909830219",
    system_prompt="""

    You are an autonomous Customer Support Triage, tasked at organizing and classifying tickets based on their urgency and category.

    1. Summarize ticket into a 3-10 word subject header.
    2. Identify the urgency. (HIGH="System down, critical issues, time pressure, money involved", MEDIUM="Technical issue, no time pressure", LOW="easily solvable, low-maintenance issue, no time pressure" )

    3. Follow a 3-step reasoning process as you verify your classification's confidence level.

    4. From the input, extract the following information to a strict output json:
    ```json
    "subject": "string" (3-10 word subject header from earlier)
    "urgency": "enum", (enum choices: [HIGH | MEDIUM | LOW])
    "category": "enum", (enum choices: [Billing | IT | Operations | Engineering | HR])
    "route": "string", (enum choices: [billing-support | it-support | eng-support | ops-internal | ops-external | hr-support])
    "confidence": "float" (confidence level of classification, limit to 2 decimal places)
    ```

    Example A:
    INPUT: "My laptop flickers rapidly during shutdown, is this normal?"
    ```
    "topic": "laptop flickering"
    "urgency": "medium",
    "category": "technical",
    "route": "eng-support",
    "confidence": 0.82
    ```
    Example B:
    INPUT: "I need to speak to your manager. They were very rude."
    ```
    "topic": "speak to manager"
    "urgency": "low",
    "category": "hr",
    "route": "hr-support",
    "confidence": 0.75
    ```
    Example C:

    INPUT: "The website is down, and I cannot access my account."
    ```
    "topic": "website down, no account access"
    "urgency": "high",
    "category": "it",
    "route": "it-support",
    "confidence": 0.92
    ```


    5. Your final response should be formatted STRICTLY as follows (INPUT, OUTPUT, REASONING):
    ```
    INPUT: "The website is down, and I cannot access my account."

    OUTPUT:
    "topic": "website down, no account access"
    "urgency": "high",
    "category": "it",
    "route": "it-support",
    "confidence": 0.92

    REASONING:
    (Explain reasoning for confidence level)
    ```
    """,
    options={"temparature": 0.1, "num_predict": 150, 'top_k': 50, 'top_p': 0.5}
)



# %%
# YOUR CODE HERE
# Leave the cell output

# TEST 2
ChatWrapper(
    user_prompt="My PHP 17000 refund pushed through, but I have yet to receieve the money despite the system telling me it was delivered. My reference number is RF00909830219",
    system_prompt="""

    You are an autonomous Customer Support Triage, tasked at organizing and classifying tickets based on their urgency and category.

    1. Summarize ticket into a 3-10 word subject header.
    2. Identify the urgency. (HIGH="System down, critical issues, time pressure, money involved", MEDIUM="Technical issue, no time pressure", LOW="easily solvable, low-maintenance issue, no time pressure" )

    3. Follow a 3-step reasoning process as you verify your classification's confidence level.

    4. From the input, extract the following information to a strict output json:
    ```json
    "subject": "string" (3-10 word subject header from earlier)
    "urgency": "enum", (enum choices: [HIGH | MEDIUM | LOW])
    "category": "enum", (enum choices: [Billing | IT | Operations | Engineering | HR])
    "route": "string", (enum choices: [billing-support | it-support | eng-support | ops-internal | ops-external | hr-support])
    "confidence": "float" (confidence level of classification, limit to 2 decimal places)
    ```

    Example A:
    INPUT: "My laptop flickers rapidly during shutdown, is this normal?"
    ```
    "topic": "laptop flickering"
    "urgency": "medium",
    "category": "technical",
    "route": "eng-support",
    "confidence": 0.82
    ```
    Example B:
    INPUT: "I need to speak to your manager. They were very rude."
    ```
    "topic": "speak to manager"
    "urgency": "low",
    "category": "hr",
    "route": "hr-support",
    "confidence": 0.75
    ```
    Example C:

    INPUT: "The website is down, and I cannot access my account."
    ```
    "topic": "website down, no account access"
    "urgency": "high",
    "category": "it",
    "route": "it-support",
    "confidence": 0.92
    ```


    5. Your final response should be formatted STRICTLY as follows (INPUT, OUTPUT, REASONING):
    ```
    INPUT: "The website is down, and I cannot access my account."

    OUTPUT:
    "topic": "website down, no account access"
    "urgency": "high",
    "category": "it",
    "route": "it-support",
    "confidence": 0.92

    REASONING:
    (Explain reasoning for confidence level)
    ```
    """,
    options={"temparature": 0.1, "num_predict": 150, 'top_k': 50, 'top_p': 0.5}
)



# %% [markdown]
# *Note down your observations, analysis and conclusions. (What were followed, what were incorrect, why you picked these prompting techniques based on the use case & what makes sense to actually use based on the results, etc.)*
# 
# 
# # <b> Observations </b>
# The responses were varied, and sometimes deviated from the given formatting. Aside from this, the LLM successfully categorized the ticket at a 92% confidence level.
# <br>
# 
# # <b> Analysis </b>
# It was imperative to fine tune the output formatting as the LLM kept on trying to revise and output slightly different from the given output. This may be due to the sheer amount of open-ended specifications given in a single prompt, requiring a much more verbose, streamlined and concise prompt in order to not confuse the LLM.
# <br>
# 
# # <b> Conclusions </b>
# This exercise highlighted the importance of structuring your prompts in order to deliver a specific business requirement. Variations in their responses can be fine tuned using different sampling parameters and additional information, structured through the use of classification, summarization, and extraction techniques. When all used in conjunction, this can effectively simulate simple-output dynamic response systems that can execute on different requirements and domains.
# 

# %% [markdown]
# # 4 Completion Checklist
# To ensure you haven't missed anything, mark the following checkboxes:
# 
# - [X] 1.2.2 Prompting and Sampling
# - [X] 2.1 Classification
#   - [X] 2.1.1 Zero-shot
#   - [X] 2.1.2 Few-shot
#   - [X] 2.1.3 CoT
#   - [X] 2.1.4 Role-based
# - [X] 2.2 Summarization
#   - [X] 2.2.1 Basic
#   - [X] 2.2.2 Constrained
#   - [X] 2.2.3 Chain-of-Thought
#   - [X] 2.2.4 Role-based
# - [X] 2.3 Extraction
#   - [X] 2.3.1 JSON Mode
#   - [X] 2.3.2 Few-shot JSON Mode
#   - [X] 2.3.3 Schema
#   - [X] 2.3.4 Combined
# - [X] 3 Customer Support Triage
#   - [X] system prompt
#     - [X] few shot
#     - [X] structured outputs (using schema definitions / JSON)
#     - [X] chain-of-thought
#     - [X] role-based
#   - [X] sampling parameters
#     - [X] temperature
#     - [X] top-k
#     - [X] top-p
#     - [X] max tokens / num_predict
#   - [X] Run multiple experiments
#   - [ ] Note down your observations, analysis and conclusions

# %% [markdown]
# # 5 Learning Resources
# 
# - https://cloud.google.com/discover/what-is-prompt-engineering
# - https://aws.amazon.com/what-is/prompt-engineering/
# - https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-engineering-guidelines.html
# - https://developers.openai.com/api/docs/guides/prompt-engineering
# - https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices
# - https://www.youtube.com/watch?v=eMlx5fFNoYc&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=7 (for attention mechanism; also check other vids in 3Blue1Brown playlist)

# %% [markdown]
# Additional suggestions:
# - Start thinking of your Capstone use cases for Week 9 (check the course outline / info session deck)
# - Form groups of up to 5 people


